/**
 * Generate one Markdown page per rule from the library's own metadata.
 *
 * The library exports its rule registry; this script walks that registry,
 * reads each rule's `meta.docs.description`, `meta.defaultOptions`,
 * `meta.schema`, and `meta.messages`, and emits a page under `en/rules/`
 * and `es/rules/`. Hand-written prose can be added in
 * `<locale>/rules/_extras/<rule>.md` and is concatenated after the
 * autogenerated block.
 *
 * Run via `pnpm -C packages/docs generate` (or implicitly via build).
 */

import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const DOCS_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const LIB_ROOT = resolve(DOCS_ROOT, '../oxlint-tailwindcss')

interface RuleMeta {
  type?: string
  docs?: { description?: string }
  fixable?: 'code' | 'whitespace'
  hasSuggestions?: boolean
  schema?: unknown
  defaultOptions?: unknown[]
  messages?: Record<string, string>
}

interface RuleExport {
  meta?: RuleMeta
  // The defineRule output also carries createOnce / create, but we don't need
  // them for documentation generation.
}

const RULE_NAMES = [
  'consistent-variant-order',
  'enforce-canonical',
  'enforce-consistent-important-position',
  'enforce-consistent-line-wrapping',
  'enforce-consistent-variable-syntax',
  'enforce-logical',
  'enforce-negative-arbitrary-values',
  'enforce-physical',
  'enforce-shorthand',
  'enforce-sort-order',
  'max-class-count',
  'no-arbitrary-value',
  'no-conflicting-classes',
  'no-contradicting-variants',
  'no-dark-without-light',
  'no-deprecated-classes',
  'no-duplicate-classes',
  'no-hardcoded-colors',
  'no-restricted-classes',
  'no-unknown-classes',
  'no-unnecessary-arbitrary-value',
  'no-unnecessary-whitespace',
  'prefer-theme-tokens',
] as const

function formatDefaultOptions(opts: unknown[] | undefined): string {
  if (!opts || opts.length === 0) return '_(no options)_\n'
  return `\`\`\`json\n${JSON.stringify(opts[0], null, 2)}\n\`\`\`\n`
}

function formatSchema(schema: unknown): string {
  if (!Array.isArray(schema) || schema.length === 0) return '_(no schema — this rule takes no options)_\n'
  const first = schema[0]
  if (!first || typeof first !== 'object') return '_(opaque schema)_\n'
  const props = (first as { properties?: Record<string, unknown> }).properties
  if (!props) return '_(no documented properties)_\n'
  const rows = Object.entries(props).map(([key, value]) => {
    const def = value as { type?: string; enum?: unknown[]; items?: { type?: string } }
    let type = def.type ?? 'unknown'
    if (def.enum) type = def.enum.map((e) => `\`"${e}"\``).join(' \\| ')
    else if (type === 'array' && def.items?.type) type = `${def.items.type}[]`
    return `| \`${key}\` | ${type} |`
  })
  return ['| Option | Type |', '|---|---|', ...rows].join('\n') + '\n'
}

function pageFor(rule: { name: string; meta?: RuleMeta }, locale: 'en' | 'es'): string {
  const meta = rule.meta ?? {}
  const description = meta.docs?.description ?? ''
  const lines: string[] = []

  lines.push(`# ${rule.name}`)
  lines.push('')
  if (description) {
    lines.push(`> ${description}`)
    lines.push('')
  }

  lines.push(locale === 'es' ? '## Opciones' : '## Options')
  lines.push('')
  lines.push(formatSchema(meta.schema))

  lines.push(locale === 'es' ? '## Valores por defecto' : '## Default values')
  lines.push('')
  lines.push(formatDefaultOptions(meta.defaultOptions))

  if (meta.fixable || meta.hasSuggestions) {
    lines.push(locale === 'es' ? '## Auto-fix' : '## Auto-fix')
    lines.push('')
    if (meta.fixable) {
      lines.push(
        locale === 'es'
          ? `- Esta regla **arregla automáticamente** (fixable: \`${meta.fixable}\`).`
          : `- This rule is **auto-fixable** (\`fixable: ${meta.fixable}\`).`,
      )
    }
    if (meta.hasSuggestions) {
      lines.push(
        locale === 'es'
          ? '- Ofrece sugerencias adicionales en el editor.'
          : '- It also offers editor suggestions for non-primary fix candidates.',
      )
    }
    lines.push('')
  }

  // Optional extras file
  const extrasPath = resolve(DOCS_ROOT, locale === 'es' ? 'es' : '', 'rules', '_extras', `${rule.name}.md`)
  if (existsSync(extrasPath)) {
    lines.push('')
    lines.push(readFileSync(extrasPath, 'utf-8').trim())
    lines.push('')
  }

  return lines.join('\n') + '\n'
}

async function main(): Promise<void> {
  // Read the published plugin shape from the built CJS bundle, which exposes
  // `{ meta, rules }` directly. Requires `pnpm -r build` to have run first
  // (the docs `build` script does this implicitly via the workspace order).
  const distPath = resolve(LIB_ROOT, 'dist/index.cjs')
  if (!existsSync(distPath)) {
    throw new Error(
      `[generate-rules] ${distPath} not found. Run \`pnpm -C packages/oxlint-tailwindcss build\` first.`,
    )
  }
  const require_ = (await import('node:module')).createRequire(import.meta.url)
  const plugin = require_(distPath) as { rules: Record<string, RuleExport> }

  for (const locale of ['en', 'es'] as const) {
    const localePrefix = locale === 'en' ? '' : 'es/'
    const outDir = resolve(DOCS_ROOT, localePrefix, 'rules')
    mkdirSync(outDir, { recursive: true })

    for (const ruleName of RULE_NAMES) {
      const exported = plugin.rules[ruleName]
      if (!exported) {
        console.warn(`[generate-rules] missing rule for ${ruleName}`)
        continue
      }
      const md = pageFor({ name: ruleName, meta: exported.meta }, locale)
      writeFileSync(resolve(outDir, `${ruleName}.md`), md, 'utf-8')
    }
  }

  console.log(`[generate-rules] wrote ${RULE_NAMES.length * 2} pages`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
