/**
 * Generate one Markdown page per rule from the library's own metadata.
 *
 * The library exports its rule registry; this script walks that registry,
 * reads each rule's `meta.docs.description`, `meta.defaultOptions`,
 * `meta.schema`, and `meta.messages`, and emits a page under `en/rules/`
 * and `es/rules/`. Hand-written prose can be added in
 * `<locale>/rules/_extras/<rule>.md` and is concatenated after the
 * autogenerated block.
 *
 * Run via `pnpm -C packages/docs generate` (or implicitly via build).
 */

import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { RULE_NAMES, oxlintPlugin, type RuleExport } from './rules.ts'

const DOCS_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')

interface RuleMeta {
  type?: string
  docs?: { description?: string }
  fixable?: 'code' | 'whitespace'
  hasSuggestions?: boolean
  schema?: unknown
  defaultOptions?: unknown[]
  messages?: Record<string, string>
}

function formatDefaultOptions(opts: unknown[] | undefined): string {
  if (!opts || opts.length === 0) return '_(no options)_\n'
  return `\`\`\`json\n${JSON.stringify(opts[0], null, 2)}\n\`\`\`\n`
}

function formatSchema(schema: unknown): string {
  if (!Array.isArray(schema) || schema.length === 0) return '_(no schema — this rule takes no options)_\n'
  const first = schema[0]
  if (!first || typeof first !== 'object') return '_(opaque schema)_\n'
  const props = (first as { properties?: Record<string, unknown> }).properties
  if (!props) return '_(no documented properties)_\n'
  const rows = Object.entries(props).map(([key, value]) => {
    const def = value as { type?: string; enum?: unknown[]; items?: { type?: string } }
    let type = def.type ?? 'unknown'
    if (def.enum) type = def.enum.map((e) => `\`"${e}"\``).join(' \\| ')
    else if (type === 'array' && def.items?.type) type = `${def.items.type}[]`
    return `| \`${key}\` | ${type} |`
  })
  return ['| Option | Type |', '|---|---|', ...rows].join('\n') + '\n'
}

function pageFor(rule: { name: string; meta?: RuleMeta }, locale: 'en' | 'es'): string {
  const meta = rule.meta ?? {}
  const description = meta.docs?.description ?? ''
  const lines: string[] = []

  lines.push(`# ${rule.name}`)
  lines.push('')
  if (description) {
    lines.push(`> ${description}`)
    lines.push('')
  }

  lines.push(locale === 'es' ? '## Opciones' : '## Options')
  lines.push('')
  lines.push(formatSchema(meta.schema))

  lines.push(locale === 'es' ? '## Valores por defecto' : '## Default values')
  lines.push('')
  lines.push(formatDefaultOptions(meta.defaultOptions))

  if (meta.fixable || meta.hasSuggestions) {
    lines.push(locale === 'es' ? '## Auto-fix' : '## Auto-fix')
    lines.push('')
    if (meta.fixable) {
      lines.push(
        locale === 'es'
          ? `- Esta regla **arregla automáticamente** (fixable: \`${meta.fixable}\`).`
          : `- This rule is **auto-fixable** (\`fixable: ${meta.fixable}\`).`,
      )
    }
    if (meta.hasSuggestions) {
      lines.push(
        locale === 'es'
          ? '- Ofrece sugerencias adicionales en el editor.'
          : '- It also offers editor suggestions for non-primary fix candidates.',
      )
    }
    lines.push('')
  }

  // Optional extras file
  const extrasPath = resolve(DOCS_ROOT, locale === 'es' ? 'es' : '', 'rules', '_extras', `${rule.name}.md`)
  if (existsSync(extrasPath)) {
    lines.push('')
    lines.push(readFileSync(extrasPath, 'utf-8').trim())
    lines.push('')
  }

  return lines.join('\n') + '\n'
}

async function main(): Promise<void> {
  for (const locale of ['en', 'es'] as const) {
    const localePrefix = locale === 'en' ? '' : 'es/'
    const outDir = resolve(DOCS_ROOT, localePrefix, 'rules')
    mkdirSync(outDir, { recursive: true })

    for (const ruleName of RULE_NAMES) {
      const exported: RuleExport = oxlintPlugin.rules[ruleName]
      const md = pageFor({ name: ruleName, meta: exported.meta }, locale)
      writeFileSync(resolve(outDir, `${ruleName}.md`), md, 'utf-8')
    }
  }

  console.log(`[generate-rules] wrote ${RULE_NAMES.length * 2} pages`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
